// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace LifePrint
{
    public partial class LifeprintDatabaseContext : DbContext
    {
        public LifeprintDatabaseContext()
        {
        }

        public LifeprintDatabaseContext(DbContextOptions<LifeprintDatabaseContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Being> Being { get; set; }
        public virtual DbSet<Health> Health { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<Social> Social { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vocation> Vocation { get; set; }
        public virtual DbSet<Wealth> Wealth { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=tcp:lifeprint.database.windows.net,1433;Initial Catalog=lifeprint-database;Persist Security Info=False;User ID=lifeprintadmin;Password=?a!$$9i#&3qX7XLQ;Multiple Active Result Sets=False;Connect Timeout=30;Encrypt=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Being>(entity =>
            {
                entity.Property(e => e.BeingId).HasColumnName("Being_ID");

                entity.Property(e => e.B10IrScore).HasColumnName("b10_ir_score");

                entity.Property(e => e.B11SaseScore).HasColumnName("b11_sase_score");

                entity.Property(e => e.B12AsdScore).HasColumnName("b12_asd_score");

                entity.Property(e => e.B13AsdScore).HasColumnName("b13_asd_score");

                entity.Property(e => e.B14AsdScore).HasColumnName("b14_asd_score");

                entity.Property(e => e.B15IrScore).HasColumnName("b15_ir_score");

                entity.Property(e => e.B16TrScore).HasColumnName("b16_tr_score");

                entity.Property(e => e.B17SaseScore).HasColumnName("b17_sase_score");

                entity.Property(e => e.B18TrScore).HasColumnName("b18_tr_score");

                entity.Property(e => e.B19PcScore).HasColumnName("b19_pc_score");

                entity.Property(e => e.B1SlScore).HasColumnName("b1_sl_score");

                entity.Property(e => e.B20SaScore).HasColumnName("b20_sa_score");

                entity.Property(e => e.B21PcScore).HasColumnName("b21_pc_score");

                entity.Property(e => e.B22SaScore).HasColumnName("b22_sa_score");

                entity.Property(e => e.B23PcScore).HasColumnName("b23_pc_score");

                entity.Property(e => e.B24SaScore).HasColumnName("b24_sa_score");

                entity.Property(e => e.B25PcScore).HasColumnName("b25_pc_score");

                entity.Property(e => e.B26SaScore).HasColumnName("b26_sa_score");

                entity.Property(e => e.B27PcScore).HasColumnName("b27_pc_score");

                entity.Property(e => e.B28SaScore).HasColumnName("b28_sa_score");

                entity.Property(e => e.B2SlScore).HasColumnName("b2_sl_score");

                entity.Property(e => e.B3SlScore).HasColumnName("b3_sl_score");

                entity.Property(e => e.B4EafeScore).HasColumnName("b4_eafe_score");

                entity.Property(e => e.B5AsdScore).HasColumnName("b5_asd_score");

                entity.Property(e => e.B6TrScore).HasColumnName("b6_tr_score");

                entity.Property(e => e.B7EafeScore).HasColumnName("b7_eafe_score");

                entity.Property(e => e.B8AsdScore).HasColumnName("b8_asd_score");

                entity.Property(e => e.B9SaseScore).HasColumnName("b9_sase_score");
            });

            modelBuilder.Entity<Health>(entity =>
            {
                entity.Property(e => e.HealthId).HasColumnName("Health_ID");

                entity.Property(e => e.H10EfScore).HasColumnName("h10_ef_score");

                entity.Property(e => e.H11EwScore).HasColumnName("h11_ew_score");

                entity.Property(e => e.H12EfScore).HasColumnName("h12_ef_score");

                entity.Property(e => e.H13EwScore).HasColumnName("h13_ew_score");

                entity.Property(e => e.H14EfScore).HasColumnName("h14_ef_score");

                entity.Property(e => e.H15GhScore).HasColumnName("h15_gh_score");

                entity.Property(e => e.H16GhScore).HasColumnName("h16_gh_score");

                entity.Property(e => e.H17GhScore).HasColumnName("h17_gh_score");

                entity.Property(e => e.H18GhScore).HasColumnName("h18_gh_score");

                entity.Property(e => e.H1GhHvsfScore).HasColumnName("h1_gh_hvsf_score");

                entity.Property(e => e.H2GhScore).HasColumnName("h2_gh_score");

                entity.Property(e => e.H3GhScore).HasColumnName("h3_gh_score");

                entity.Property(e => e.H4GhScore).HasColumnName("h4_gh_score");

                entity.Property(e => e.H5GhScore).HasColumnName("h5_gh_score");

                entity.Property(e => e.H6EfScore).HasColumnName("h6_ef_score");

                entity.Property(e => e.H7EwScore).HasColumnName("h7_ew_score");

                entity.Property(e => e.H8EwScore).HasColumnName("h8_ew_score");

                entity.Property(e => e.H9EwScore).HasColumnName("h9_ew_score");

                entity.Property(e => e.HEfPercent2dpScore).HasColumnName("h_ef_percent_2dp_score");

                entity.Property(e => e.HEfTotScore).HasColumnName("h_ef_tot_score");

                entity.Property(e => e.HEwPercent2dpScore).HasColumnName("h_ew_percent_2dp_score");

                entity.Property(e => e.HEwTotScore).HasColumnName("h_ew_tot_score");

                entity.Property(e => e.HGhPercent2dpScore).HasColumnName("h_gh_percent_2dp_score");

                entity.Property(e => e.HGhTotScore).HasColumnName("h_gh_tot_score");

                entity.Property(e => e.HHvsfPercent2dpScore).HasColumnName("h_hvsf_percent_2dp_score");

                entity.Property(e => e.HHvsfTotScore).HasColumnName("h_hvsf_tot_score");

                entity.Property(e => e.HPercent2dpScore).HasColumnName("h_percent_2dp_score");
            });

            modelBuilder.Entity<Results>(entity =>
            {
                entity.HasKey(e => e.ResultId)
                    .HasName("PK__Results__5E08F5430758CD8E");

                entity.Property(e => e.ResultId).HasColumnName("Result_ID");

                entity.Property(e => e.BeingId).HasColumnName("Being_ID");

                entity.Property(e => e.HealthId).HasColumnName("Health_ID");

                entity.Property(e => e.ResultDate)
                    .HasColumnType("datetime")
                    .HasColumnName("Result_Date");

                entity.Property(e => e.SocialId).HasColumnName("Social_ID");

                entity.Property(e => e.UserEmail)
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnName("User_Email");

                entity.Property(e => e.VocationId).HasColumnName("Vocation_ID");

                entity.Property(e => e.WealthId).HasColumnName("Wealth_ID");

                entity.HasOne(d => d.Being)
                    .WithMany(p => p.Results)
                    .HasForeignKey(d => d.BeingId)
                    .HasConstraintName("FK__Results__Being_I__02084FDA");

                entity.HasOne(d => d.Health)
                    .WithMany(p => p.Results)
                    .HasForeignKey(d => d.HealthId)
                    .HasConstraintName("FK__Results__Health___01142BA1");

                entity.HasOne(d => d.Social)
                    .WithMany(p => p.Results)
                    .HasForeignKey(d => d.SocialId)
                    .HasConstraintName("FK__Results__Social___03F0984C");

                entity.HasOne(d => d.UserEmailNavigation)
                    .WithMany(p => p.Results)
                    .HasForeignKey(d => d.UserEmail)
                    .HasConstraintName("FK__Results__User_Em__6FE99F9F");

                entity.HasOne(d => d.Vocation)
                    .WithMany(p => p.Results)
                    .HasForeignKey(d => d.VocationId)
                    .HasConstraintName("FK__Results__Vocatio__1F98B2C1");

                entity.HasOne(d => d.Wealth)
                    .WithMany(p => p.Results)
                    .HasForeignKey(d => d.WealthId)
                    .HasConstraintName("FK__Results__Wealth___02FC7413");
            });

            modelBuilder.Entity<Social>(entity =>
            {
                entity.Property(e => e.SocialId).HasColumnName("Social_ID");

                entity.Property(e => e.S10NScore).HasColumnName("s10_n_score");

                entity.Property(e => e.S11CScore).HasColumnName("s11_c_score");

                entity.Property(e => e.S12EScore).HasColumnName("s12_e_score");

                entity.Property(e => e.S13FmScore).HasColumnName("s13_fm_score");

                entity.Property(e => e.S14FmScore).HasColumnName("s14_fm_score");

                entity.Property(e => e.S15FrScore).HasColumnName("s15_fr_score");

                entity.Property(e => e.S16PScore).HasColumnName("s16_p_score");

                entity.Property(e => e.S17RScore).HasColumnName("s17_r_score");

                entity.Property(e => e.S18EScore).HasColumnName("s18_e_score");

                entity.Property(e => e.S19NScore).HasColumnName("s19_n_score");

                entity.Property(e => e.S20CScore).HasColumnName("s20_c_score");

                entity.Property(e => e.S2HvsfScore).HasColumnName("s2_hvsf_score");

                entity.Property(e => e.S3FmScore).HasColumnName("s3_fm_score");

                entity.Property(e => e.S4FmScore).HasColumnName("s4_fm_score");

                entity.Property(e => e.S5FrScore).HasColumnName("s5_fr_score");

                entity.Property(e => e.S6FrScore).HasColumnName("s6_fr_score");

                entity.Property(e => e.S7PScore).HasColumnName("s7_p_score");

                entity.Property(e => e.S8RScore).HasColumnName("s8_r_score");

                entity.Property(e => e.S9NScore).HasColumnName("s9_n_score");
            });

            modelBuilder.Entity<Users>(entity =>
            {
                entity.HasKey(e => e.UserEmail)
                    .HasName("PK__Users__4C70A05DADC8B01C");

                entity.Property(e => e.UserEmail)
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnName("User_Email");

                entity.Property(e => e.UserLearnWorldsId).HasColumnName("User_Learn_Worlds_ID");

                entity.Property(e => e.UserPassword)
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnName("User_Password");
            });

            modelBuilder.Entity<Vocation>(entity =>
            {
                entity.Property(e => e.VocationId).HasColumnName("Vocation_ID");

                entity.Property(e => e.V10PImPfbcynScore).HasColumnName("v10_p_im_pfbcyn_score");

                entity.Property(e => e.V11IImScore).HasColumnName("v11_i_im_score");

                entity.Property(e => e.V12FlCgscore).HasColumnName("v12_fl_cgscore");

                entity.Property(e => e.V13DPfbcynScore).HasColumnName("v13_d_pfbcyn_score");

                entity.Property(e => e.V14IScore).HasColumnName("v14_i_score");

                entity.Property(e => e.V15FlSocScore).HasColumnName("v15_fl_soc_score");

                entity.Property(e => e.V16PImscore).HasColumnName("v16_p_imscore");

                entity.Property(e => e.V17DFlAamScore).HasColumnName("v17_d_fl_aam_score");

                entity.Property(e => e.V18FlUfPfbeffScore).HasColumnName("v18_fl_uf_pfbeff_score");

                entity.Property(e => e.V19IScore).HasColumnName("v19_i_score");

                entity.Property(e => e.V1PPfbexhScore).HasColumnName("v1_p_pfbexh_score");

                entity.Property(e => e.V20PResScore).HasColumnName("v20_p_res_score");

                entity.Property(e => e.V21FlAePfbeffScore).HasColumnName("v21_fl_ae_pfbeff_score");

                entity.Property(e => e.V22IResScore).HasColumnName("v22_i_res_score");

                entity.Property(e => e.V23PResScore).HasColumnName("v23_p_res_score");

                entity.Property(e => e.V24VaFlAeScore).HasColumnName("v24_va_fl_ae_score");

                entity.Property(e => e.V25VaFlAeScore).HasColumnName("v25_va_fl_ae_score");

                entity.Property(e => e.V26VaFlCgScore).HasColumnName("v26_va_fl_cg_score");

                entity.Property(e => e.V27VaPafulPfbeffScore).HasColumnName("v27_va_paful_pfbeff_score");

                entity.Property(e => e.V28VaPacapScore).HasColumnName("v28_va_pacap_score");

                entity.Property(e => e.V29VaOafulScore).HasColumnName("v29_va_oaful_score");

                entity.Property(e => e.V2FlCsbResScore).HasColumnName("v2_fl_csb_res_score");

                entity.Property(e => e.V30VaOatrtEmPfbeffScore).HasColumnName("v30_va_oatrt_em_pfbeff_score");

                entity.Property(e => e.V31VaPatrtEmScore).HasColumnName("v31_va_patrt_em_score");

                entity.Property(e => e.V32VaOacapRscEmPfbrscScore).HasColumnName("v32_va_oacap_rsc_em_pfbrsc_score");

                entity.Property(e => e.V33VaOatrtPfbcynScore).HasColumnName("v33_va_oatrt_pfbcyn_score");

                entity.Property(e => e.V34VaPatrtEmPfbcynScore).HasColumnName("v34_va_patrt_em_pfbcyn_score");

                entity.Property(e => e.V35VaOacapDmdPfbdmdScore).HasColumnName("v35_va_oacap_dmd_pfbdmd_score");

                entity.Property(e => e.V3DMpScore).HasColumnName("v3_d_mp_score");

                entity.Property(e => e.V4FlAamScore).HasColumnName("v4_fl_aam_score");

                entity.Property(e => e.V5IFlTrotScore).HasColumnName("v5_i_fl_trot_score");

                entity.Property(e => e.V6PPfbexhScore).HasColumnName("v6_p_pfbexh_score");

                entity.Property(e => e.V7DScore).HasColumnName("v7_d_score");

                entity.Property(e => e.V8IFlCotahScore).HasColumnName("v8_i_fl_cotah_score");

                entity.Property(e => e.V9DImScore).HasColumnName("v9_d_im_score");
            });

            modelBuilder.Entity<Wealth>(entity =>
            {
                entity.Property(e => e.WealthId).HasColumnName("Wealth_ID");

                entity.Property(e => e.W10FwoCwpScore).HasColumnName("w10_fwo_cwp_score");

                entity.Property(e => e.W1WsCwpScore).HasColumnName("w1_ws_cwp_score");

                entity.Property(e => e.W2WsCwpScore).HasColumnName("w2_ws_cwp_score");

                entity.Property(e => e.W3WsCwpScore).HasColumnName("w3_ws_cwp_score");

                entity.Property(e => e.W4WsCwpScore).HasColumnName("w4_ws_cwp_score");

                entity.Property(e => e.W5CwlScore).HasColumnName("w5_cwl_score");

                entity.Property(e => e.W6CwlScore).HasColumnName("w6_cwl_score");

                entity.Property(e => e.W7CwlScore).HasColumnName("w7_cwl_score");

                entity.Property(e => e.W8FwoCwpScore).HasColumnName("w8_fwo_cwp_score");

                entity.Property(e => e.W9FwoCwpScore).HasColumnName("w9_fwo_cwp_score");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}