// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifePrint
{
    public partial class Social
    {
        public Social()
        {
            Results = new HashSet<Results>();
        }

        public int SocialId { get; set; }
        public int? S2HvsfScore { get; set; }
        public int? S3FmScore { get; set; }
        public int? S4FmScore { get; set; }
        public int? S5FrScore { get; set; }
        public int? S6FrScore { get; set; }
        public int? S7PScore { get; set; }
        public int? S8RScore { get; set; }
        public int? S9NScore { get; set; }
        public int? S10NScore { get; set; }
        public int? S11CScore { get; set; }
        public int? S12EScore { get; set; }
        public int? S13FmScore { get; set; }
        public int? S14FmScore { get; set; }
        public int? S15FrScore { get; set; }
        public int? S16PScore { get; set; }
        public int? S17RScore { get; set; }
        public int? S18EScore { get; set; }
        public int? S19NScore { get; set; }
        public int? S20CScore { get; set; }

        public virtual ICollection<Results> Results { get; set; }
    }
}