// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifePrint
{
    public partial class Users
    {
        public Users()
        {
            Results = new HashSet<Results>();
        }

        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public int UserLearnWorldsId { get; set; }

        public virtual ICollection<Results> Results { get; set; }
    }
}