// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifePrint
{
    public partial class Vocation
    {
        public Vocation()
        {
            Results = new HashSet<Results>();
        }

        public int VocationId { get; set; }
        public int? V1PPfbexhScore { get; set; }
        public int? V2FlCsbResScore { get; set; }
        public int? V3DMpScore { get; set; }
        public int? V4FlAamScore { get; set; }
        public int? V5IFlTrotScore { get; set; }
        public int? V6PPfbexhScore { get; set; }
        public int? V7DScore { get; set; }
        public int? V8IFlCotahScore { get; set; }
        public int? V9DImScore { get; set; }
        public int? V10PImPfbcynScore { get; set; }
        public int? V11IImScore { get; set; }
        public int? V12FlCgscore { get; set; }
        public int? V13DPfbcynScore { get; set; }
        public int? V14IScore { get; set; }
        public int? V15FlSocScore { get; set; }
        public int? V16PImscore { get; set; }
        public int? V17DFlAamScore { get; set; }
        public int? V18FlUfPfbeffScore { get; set; }
        public int? V19IScore { get; set; }
        public int? V20PResScore { get; set; }
        public int? V21FlAePfbeffScore { get; set; }
        public int? V22IResScore { get; set; }
        public int? V23PResScore { get; set; }
        public int? V24VaFlAeScore { get; set; }
        public int? V25VaFlAeScore { get; set; }
        public int? V26VaFlCgScore { get; set; }
        public int? V27VaPafulPfbeffScore { get; set; }
        public int? V28VaPacapScore { get; set; }
        public int? V29VaOafulScore { get; set; }
        public int? V30VaOatrtEmPfbeffScore { get; set; }
        public int? V31VaPatrtEmScore { get; set; }
        public int? V32VaOacapRscEmPfbrscScore { get; set; }
        public int? V33VaOatrtPfbcynScore { get; set; }
        public int? V34VaPatrtEmPfbcynScore { get; set; }
        public int? V35VaOacapDmdPfbdmdScore { get; set; }

        public virtual ICollection<Results> Results { get; set; }
    }
}